'''
Before import this, call schema.generate_name_file()
Or, import schema first.
This is auto-generated file. DO NOT MODIFY!
'''
map_data_rel2rel_chunk = 'map_data_rel2rel_chunk'
data = 'data'
name = 'name'
file = 'file'
value = 'value'
type = 'type'
size = 'size'
source = 'source'
aid = 'aid'
data_relation = 'data_relation'
path = 'path'
uuid = 'uuid'
bid = 'bid'
inp = 'inp'
revision = 'revision'
md5 = 'md5'
out = 'out'