'''
Before import this, call schema.generate_name_file()
Or, import schema first.
This is auto-generated file. DO NOT MODIFY!
'''
aid = 'aid'
bid = 'bid'
data = 'data'
data_relation = 'data_relation'
file = 'file'
inp = 'inp'
md5 = 'md5'
name = 'name'
named_relations2data_relation = 'named_relations2data_relation'
out = 'out'
path = 'path'
revision = 'revision'
size = 'size'
source = 'source'
type = 'type'
uuid = 'uuid'
value = 'value'