'''
Before import this, call schema.generate_name_file()
Or, import schema first.
This is auto-generated file. DO NOT MODIFY!
'''
aid = 'aid'
bid = 'bid'
data = 'data'
data_relation = 'data_relation'
dataset = 'dataset'
dev_name = 'dev_name'
dev_revision = 'dev_revision'
dev_size = 'dev_size'
file = 'file'
inp = 'inp'
md5 = 'md5'
name = 'name'
named_relations = 'named_relations'
named_relations2data_relation = 'named_relations2data_relation'
out = 'out'
path = 'path'
revision = 'revision'
size = 'size'
source = 'source'
test_name = 'test_name'
test_revision = 'test_revision'
test_size = 'test_size'
train_name = 'train_name'
train_revision = 'train_revision'
train_size = 'train_size'
type = 'type'
uuid = 'uuid'
value = 'value'